/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.etracs.ticketing.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author wflores 
 */
@StyleSheet 
@Template(CrudFormPage.class)
public class RoutePage extends javax.swing.JPanel {

    /**
     * Creates new form RoutePage
     */
    public RoutePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLabel2 = new com.rameses.rcp.control.XLabel();

        setMinimumSize(new java.awt.Dimension(750, 256));
        setPreferredSize(new java.awt.Dimension(750, 256));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("  General Information     ");
        jPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(100);
        xFormPanel1.setCellspacing(4);

        xTextField1.setCaption("Title");
        xTextField1.setName("entity.name"); // NOI18N
        xTextField1.setRequired(true);
        xTextField1.setStretchWidth(100);
        xFormPanel1.add(xTextField1);

        xIntegerField1.setCaption("Sort Order");
        xIntegerField1.setName("entity.sortorder"); // NOI18N
        xIntegerField1.setCellPadding(new java.awt.Insets(0, 0, 15, 0));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xLookupField1.setCaption("Origin");
        xLookupField1.setExpression("#{(item ? [item.objid, item.name].join(' - ') : '')}");
        xLookupField1.setHandler("lookupOrg");
        xLookupField1.setName("entity.origin"); // NOI18N
        xLookupField1.setIndex(4);
        xLookupField1.setRequired(true);
        xLookupField1.setStretchWidth(100);
        xFormPanel1.add(xLookupField1);

        xLabel1.setCaption(" ");
        xLabel1.setDepends(new String[] {"entity.origin"});
        xLabel1.setExpression("#{entity.origin.address}");
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel1.setPreferredSize(new java.awt.Dimension(100, 20));
        xLabel1.setStretchWidth(100);
        xFormPanel1.add(xLabel1);

        xLookupField2.setCaption("Destination");
        xLookupField2.setExpression("#{(item ? [item.objid, item.name].join(' - ') : '')}");
        xLookupField2.setHandler("lookupOrg");
        xLookupField2.setName("entity.destination"); // NOI18N
        xLookupField2.setCellPadding(new java.awt.Insets(15, 0, 0, 0));
        xLookupField2.setIndex(4);
        xLookupField2.setStretchWidth(100);
        xFormPanel1.add(xLookupField2);

        xLabel2.setCaption(" ");
        xLabel2.setDepends(new String[] {"entity.destination"});
        xLabel2.setExpression("#{entity.destination.address}");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel2.setPreferredSize(new java.awt.Dimension(100, 20));
        xLabel2.setStretchWidth(100);
        xFormPanel1.add(xLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
