/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.etracs.ticketing.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author wflores
 */
@Template(FormPage.class)
public class TerminalPassVerifyPage extends javax.swing.JPanel {

    /**
     * Creates new form TerminalPassVerifyPage
     */
    public TerminalPassVerifyPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMinimumSize(new java.awt.Dimension(542, 286));
        setPreferredSize(new java.awt.Dimension(542, 286));
        setLayout(new java.awt.BorderLayout());

        xFormPanel1.setCaptionFontStyle("font-size: 14;");
        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(100);
        xFormPanel1.setCellspacing(5);
        xFormPanel1.setPadding(new java.awt.Insets(0, 5, 5, 0));

        xComboBox1.setCaption("Turnstile");
        xComboBox1.setExpression("#{item.title}");
        xComboBox1.setItems("turnstiles");
        xComboBox1.setName("entity.turnstile"); // NOI18N
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaptionFontStyle("font-size:14;");
        xComboBox1.setFontStyle("font-size: 14;");
        xComboBox1.setPreferredSize(new java.awt.Dimension(100, 30));
        xComboBox1.setRequired(true);
        xComboBox1.setStretchWidth(100);
        xFormPanel1.add(xComboBox1);

        xTextField1.setCaption("Barcode");
        xTextField1.setName("entity.barcode"); // NOI18N
        xTextField1.setCaptionFontStyle("font-size:14;");
        xTextField1.setFontStyle("font-size: 14;");
        xTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
        xTextField1.setRequired(true);
        xTextField1.setStretchWidth(100);
        xFormPanel1.add(xTextField1);

        xPanel1.setCaption(" ");
        xPanel1.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        xPanel1.setStretchWidth(100);
        xPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        xButton1.setMnemonic('v');
        xButton1.setName("verify"); // NOI18N
        xButton1.setDefaultCommand(true);
        xButton1.setFontStyle("font-size:14;");
        xButton1.setText("Verify");
        xPanel1.add(xButton1);

        xButton2.setMnemonic('c');
        xButton2.setName("cancel"); // NOI18N
        xButton2.setFontStyle("font-size:14;");
        xButton2.setImmediate(true);
        xButton2.setText("Cancel");
        xPanel1.add(xButton2);

        xFormPanel1.add(xPanel1);

        add(xFormPanel1, java.awt.BorderLayout.CENTER);

        xLabel1.setExpression("#{msg}");
        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel1.setName("msg"); // NOI18N
        xLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        xLabel1.setFontStyle("font-size: 16; font-weight: bold;");
        xLabel1.setForeground(new java.awt.Color(0, 0, 153));
        xLabel1.setShowCaption(false);
        add(xLabel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
