/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.etracs.ticketing.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class TicketingCashReceiptPage1 extends javax.swing.JPanel {

    /**
     * Creates new form TicketingCashReceiptPage1
     */
    public TicketingCashReceiptPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInitial = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField4 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField5 = new com.rameses.rcp.control.XIntegerField();

        setMinimumSize(new java.awt.Dimension(586, 313));
        setPreferredSize(new java.awt.Dimension(586, 313));
        setLayout(new java.awt.BorderLayout());

        pnlInitial.setLayout(new java.awt.BorderLayout());

        xFormPanel2.setCaptionFontStyle("font-size:14;");
        xFormPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel2.setCaptionWidth(150);
        xFormPanel2.setCellspacing(4);

        xLabel5.setCaption("Route");
        xLabel5.setExpression("#{ entity.route.name }");
        xLabel5.setName(""); // NOI18N
        xLabel5.setVisibleWhen("");
        xLabel5.setCellPadding(new java.awt.Insets(25, 30, 0, 0));
        xLabel5.setFontStyle("font-size:18; font-weight: bold;");
        xLabel5.setForeground(new java.awt.Color(50, 50, 50));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 30));
        xLabel5.setShowCaption(false);
        xFormPanel2.add(xLabel5);

        xLabel6.setCaption("Route");
        xLabel6.setName(""); // NOI18N
        xLabel6.setVisibleWhen("");
        xLabel6.setCellPadding(new java.awt.Insets(15, 30, 5, 0));
        xLabel6.setFontStyle("font-size:16; font-weight: bold;");
        xLabel6.setForeground(new java.awt.Color(50, 50, 50));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 24));
        xLabel6.setShowCaption(false);
        xLabel6.setText("General Information");
        xFormPanel2.add(xLabel6);

        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(150);
        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel1.setShowCaption(false);
        xFormPanel1.setStretchWidth(100);

        xLabel2.setCaption("Receipt Number");
        xLabel2.setExpression("#{entity.receiptno}");
        xLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)), javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 2)));
        xLabel2.setCaptionFontStyle("font-size:14;");
        xLabel2.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xLabel2.setFontStyle("font-size:14;font-weight: bold;");
        xLabel2.setForeground(new java.awt.Color(30, 30, 30));
        xLabel2.setPreferredSize(new java.awt.Dimension(200, 25));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Receipt Date");
        xLabel3.setExpression("#{entity.receiptdate}");
        xLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)), javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 2)));
        xLabel3.setCaptionFontStyle("font-size:14");
        xLabel3.setCaptionWidth(110);
        xLabel3.setCellPadding(new java.awt.Insets(0, 28, 0, 0));
        xLabel3.setFontStyle("font-size:14;");
        xLabel3.setForeground(new java.awt.Color(30, 30, 30));
        xLabel3.setPreferredSize(new java.awt.Dimension(200, 25));
        xFormPanel1.add(xLabel3);

        xFormPanel2.add(xFormPanel1);

        xTextField1.setCaption("Paid By");
        xTextField1.setName("entity.paidby"); // NOI18N
        xTextField1.setCaptionFontStyle("font-size:14;");
        xTextField1.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xTextField1.setFontStyle("font-size:14;");
        xTextField1.setPreferredSize(new java.awt.Dimension(540, 25));
        xTextField1.setRequired(true);
        xFormPanel2.add(xTextField1);

        xTextField2.setCaption("Address");
        xTextField2.setName("entity.paidbyaddress"); // NOI18N
        xTextField2.setCaptionFontStyle("font-size:14;");
        xTextField2.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xTextField2.setFontStyle("font-size:14;");
        xTextField2.setPreferredSize(new java.awt.Dimension(540, 25));
        xTextField2.setRequired(true);
        xFormPanel2.add(xTextField2);

        xLabel7.setCaption("Route");
        xLabel7.setExpression("Guest Information");
        xLabel7.setName(""); // NOI18N
        xLabel7.setVisibleWhen("");
        xLabel7.setCellPadding(new java.awt.Insets(15, 30, 5, 0));
        xLabel7.setFontStyle("font-size:14; font-weight: bold;");
        xLabel7.setForeground(new java.awt.Color(50, 50, 50));
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 24));
        xLabel7.setShowCaption(false);
        xFormPanel2.add(xLabel7);

        xIntegerField1.setCaption("No. of Adults");
        xIntegerField1.setName("numadult"); // NOI18N
        xIntegerField1.setCaptionFontStyle("font-size:14;");
        xIntegerField1.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xIntegerField1.setFontStyle("font-size:14");
        xIntegerField1.setPreferredSize(new java.awt.Dimension(100, 24));
        xIntegerField1.setRequired(true);
        xFormPanel2.add(xIntegerField1);

        xIntegerField2.setCaption("No. of Senior");
        xIntegerField2.setName("numsenior"); // NOI18N
        xIntegerField2.setCaptionFontStyle("font-size:14;");
        xIntegerField2.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xIntegerField2.setFontStyle("font-size:14");
        xIntegerField2.setPreferredSize(new java.awt.Dimension(100, 24));
        xIntegerField2.setRequired(true);
        xFormPanel2.add(xIntegerField2);

        xIntegerField3.setCaption("No. of Children");
        xIntegerField3.setName("numchildren"); // NOI18N
        xIntegerField3.setCaptionFontStyle("font-size:14");
        xIntegerField3.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xIntegerField3.setFontStyle("font-size:14");
        xIntegerField3.setPreferredSize(new java.awt.Dimension(100, 24));
        xIntegerField3.setRequired(true);
        xFormPanel2.add(xIntegerField3);

        xIntegerField4.setCaption("No. of Filipinos");
        xIntegerField4.setName("numfil"); // NOI18N
        xIntegerField4.setCaptionFontStyle("font-size:14");
        xIntegerField4.setCellPadding(new java.awt.Insets(25, 45, 0, 0));
        xIntegerField4.setFontStyle("font-size:14");
        xIntegerField4.setPreferredSize(new java.awt.Dimension(100, 24));
        xIntegerField4.setRequired(true);
        xFormPanel2.add(xIntegerField4);

        xIntegerField5.setCaption("No. of Non-Filipinos");
        xIntegerField5.setName("numnonfil"); // NOI18N
        xIntegerField5.setCaptionFontStyle("font-size:14");
        xIntegerField5.setCellPadding(new java.awt.Insets(0, 45, 0, 0));
        xIntegerField5.setFontStyle("font-size:14");
        xIntegerField5.setPreferredSize(new java.awt.Dimension(100, 24));
        xIntegerField5.setRequired(true);
        xFormPanel2.add(xIntegerField5);

        pnlInitial.add(xFormPanel2, java.awt.BorderLayout.CENTER);

        add(pnlInitial, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XPanel pnlInitial;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    private com.rameses.rcp.control.XIntegerField xIntegerField4;
    private com.rameses.rcp.control.XIntegerField xIntegerField5;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
