/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.etracs.ticketing.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class TicketingCashReceiptPage extends javax.swing.JPanel {

    /**
     * Creates new form TicketingCashReceiptPage
     */
    public TicketingCashReceiptPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnlInitial = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField4 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField5 = new com.rameses.rcp.control.XIntegerField();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        xFormPanel2.setCaptionWidth(150);

        xLabel1.setCaption("Select a transaction");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 18));
        xLabel1.setShowCaption(false);
        xLabel1.setText("Enter Info");
        xFormPanel2.add(xLabel1);

        xLabel5.setCaption("Route");
        xLabel5.setExpression("#{ entity.route }");
        xLabel5.setName(""); // NOI18N
        xLabel5.setVisibleWhen("");
        xLabel5.setCellPadding(new java.awt.Insets(30, 30, 0, 0));
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel5);

        xIntegerField1.setCaption("No. of Adults");
        xIntegerField1.setName("numadult"); // NOI18N
        xIntegerField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xFormPanel2.add(xIntegerField1);

        xIntegerField2.setCaption("No. of Senior");
        xIntegerField2.setName("numsenior"); // NOI18N
        xIntegerField2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xFormPanel2.add(xIntegerField2);

        xIntegerField3.setCaption("No. of Children");
        xIntegerField3.setName("numchildren"); // NOI18N
        xIntegerField3.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xFormPanel2.add(xIntegerField3);

        xIntegerField4.setCaption("No. of Filipinos");
        xIntegerField4.setName("numfil"); // NOI18N
        xIntegerField4.setCellPadding(new java.awt.Insets(30, 30, 0, 0));
        xFormPanel2.add(xIntegerField4);

        xIntegerField5.setCaption("No. of Non-filipinos");
        xIntegerField5.setName("numnonfil"); // NOI18N
        xIntegerField5.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xFormPanel2.add(xIntegerField5);

        javax.swing.GroupLayout pnlInitialLayout = new javax.swing.GroupLayout(pnlInitial);
        pnlInitial.setLayout(pnlInitialLayout);
        pnlInitialLayout.setHorizontalGroup(
            pnlInitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        pnlInitialLayout.setVerticalGroup(
            pnlInitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jPanel5.add(pnlInitial, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private com.rameses.rcp.control.XPanel pnlInitial;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    private com.rameses.rcp.control.XIntegerField xIntegerField4;
    private com.rameses.rcp.control.XIntegerField xIntegerField5;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel5;
    // End of variables declaration//GEN-END:variables
}
